# @package _global_
bins: 255

model:
  net_kwargs: ${net_kwargs}
  critic_kwargs: ${critic_kwargs}
  act_kwargs: ${act_kwargs}
  # Hyperparameters
  action_entropy_coef: 5e-3
  action_std_scale: 2e1
  critic_loss_scale: 2
  useless_fine_scale: 0 #1e-9
  ppo_clip: 0.2

net_kwargs:
  hidden_sizes:
    - 256
    - 128
    # - 256
  layers_cfg: ${layer_cfg}


critic_kwargs:
  hidden_sizes:
    # - 512
    - 512
    - 256
    - 128
  linear_kwargs: ${layer_cfg}
  out_kwargs: ${output_layer_cfg}
  out_features: ${bins}

act_kwargs:
  hidden_sizes:
    - 512
    - 256
    - 128
  linear_kwargs: ${layer_cfg}
  out_kwargs: ${actor_output_layer_cfg}

layer_cfg:
  act_fn: silu
  norm_layer: LayerNorm
  init_kwargs: ${init}
  use_bias: False

output_layer_cfg:
  act_fn: None
  norm_layer: None
  init_kwargs: ${zero_init}
  use_bias: True

actor_output_layer_cfg:
  act_fn: None
  norm_layer: None
  init_kwargs: ${zero_init}
  use_bias: True

init:
  scale: 1.13
  mode: fan_avg
  distribution: truncated_normal

zero_init:
  scale: 0.0
  mode: fan_avg
  distribution: truncated_normal
