n_envs: 4096
show_viewer: False
sticky: 1
max_t: 3600
trunc_is_done: False
randomize_box: True
vis_conf:
  n_rendered_envs: 1
ur5e_config:
  control_mode: delta
  control_type: position
  action_scale: 3e-3
  randomize_hand: True
reward_scales:
  grasped_pos: 0.03
  grasped_height: 0.15
  overdraft: -1
  asymmetry: -1e-5
  sq_distance: -0.1
  distance: -0.05
  ee_quat_delta: -1e-5
