n_envs: 4096
show_viewer: False
sticky: 1
max_t: 720
trunc_is_done: False
vis_conf:
  n_rendered_envs: 1
ur5e_config:
  control_mode: delta
  control_type: position
  action_scale: 3e-3
  randomize_hand: True
reward_scales:
  grasped_pos: 0.03
  grasped_height: 1.5
  overdraft: -1
  asymmetry: -1e-5
  sq_distance: -0.1
  distance: -0.05
  ee_quat_delta: -1e-5
object_configs:
  # - kind: box
  #   params:
  #     size: 0.03
  # - kind: box
  #   params:
  #     size: 0.04
  # - kind: mesh
  #   params:
  #     file: base.stl
  # - kind: box
  #   params:
  #     size:
  #       - 0.06
  #       - 0.02
  #       - 0.03
  - kind: sphere
    params:
      radius: 0.02
  # - kind: cylinder
  #   params:
  #     height: 0.04
  #     radius: 0.02
  # - kind: cylinder
  #   params:
  #     height: 0.06
  #     radius: 0.016
